# ==========================================
# 1. ELASTICSEARCH (Single Node Mode)
# ==========================================
apiVersion: v1
kind: Service
metadata:
  name: elasticsearch
  namespace: job7189-monitoring
spec:
  type: ClusterIP
  ports:
  - port: 9200
    targetPort: 9200
  selector:
    app: elasticsearch
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: es
  namespace: job7189-monitoring
spec:
  serviceName: elasticsearch
  replicas: 1 # <--- CHỈ 1 NODE
  selector:
    matchLabels:
      app: elasticsearch
  template:
    metadata:
      labels:
        app: elasticsearch
    spec:
      initContainers:
      - name: fix-permissions
        image: busybox
        command: ["sh", "-c", "chown -R 1000:1000 /usr/share/elasticsearch/data"]
        volumeMounts:
        - name: data
          mountPath: /usr/share/elasticsearch/data
      containers:
      - name: elasticsearch
        image: docker.elastic.co/elasticsearch/elasticsearch:7.17.18
        ports:
        - containerPort: 9200
        resources:
          limits:
            memory: 1Gi # Giới hạn 1GB RAM để không sập máy
          requests:
            memory: 512Mi
        env:
        # QUAN TRỌNG: Chế độ 1 node, không cần tìm đồng đội
        - name: discovery.type
          value: "single-node"
        
        - name: ES_JAVA_OPTS
          value: "-Xms512m -Xmx512m"
        - name: xpack.security.enabled
          value: "false" # Tắt login user/pass cho nhẹ
        volumeMounts:
        - name: data
          mountPath: /usr/share/elasticsearch/data
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 2Gi # 2GB ổ cứng là đủ test

---
# ==========================================
# 2. KIBANA (Giao diện quản lý)
# ==========================================
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kibana
  namespace: job7189-monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kibana
  template:
    metadata:
      labels:
        app: kibana
    spec:
      containers:
      - name: kibana
        image: docker.elastic.co/kibana/kibana:7.17.18
        ports:
        - containerPort: 5601
        env:
        - name: ELASTICSEARCH_HOSTS
          value: "http://elasticsearch:9200"
        - name: XPACK_ENCRYPTEDSAVEDOBJECTS_ENCRYPTIONKEY
          value: "68169b82ac04340cc20ee03a6b6b879b47ae27b6443a9602f4a8ca2858779906"
        - name: XPACK_REPORTING_ENCRYPTIONKEY
          value: "4993bac4970d25766c6bb768fb7106bc7b63ace470c28da61d55b4e4ba569031"
        - name: XPACK_SECURITY_ENCRYPTIONKEY
          value: "bdb94ef8471fd4580301f65689b081bac9d9c02ad2f77ca6cbc0724c468f5f5b"  
---
apiVersion: v1
kind: Service
metadata:
  name: kibana
  namespace: job7189-monitoring
spec:
  type: NodePort
  ports:
  - port: 5601
    targetPort: 5601
    nodePort: 30601
  selector:
    app: kibana