parent=keycloak
import=common/keycloak

# QUAN TRỌNG: Khai báo file CSS của bạn SAU các file CSS của theme cha.
# Điều này cho phép CSS của bạn ghi đè lên các style mặc định.
# 'login.css' là file CSS mặc định của theme 'keycloak' hoặc 'base'.
# 'custom-vietcv-login.css' là file CSS tùy chỉnh của bạn.
styles=css/login.css css/custom-vietcv-login.css

# Ví dụ một số class bạn có thể muốn giữ để nhắm mục tiêu:
kcHtmlClass=login-pf # Class trên thẻ <html> hoặc <body>
kcLoginClass=login-pf-page # Class cho trang login tổng thể
kcFormCardClass=card-pf # Class cho card chứa form
kcInputClass=pf-c-form-control # Class cho các trường input
kcButtonClass=pf-c-button # Class chung cho các nút
kcButtonPrimaryClass=pf-m-primary # Class cho nút chính