apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-internal-reload-token
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}
type: Opaque
data:
  token: {{ .Values.internalReloadToken | b64enc | quote }}
