log_errors=1
error_log=/dev/stderr
display_errors=0
display_startup_errors=0
expose_php=0

memory_limit=192M
max_execution_time=30
max_input_time=60

post_max_size=20M
upload_max_filesize=20M

realpath_cache_size=4096K
realpath_cache_ttl=600

opcache.enable=1
opcache.enable_cli=0
opcache.memory_consumption=96
opcache.interned_strings_buffer=16
opcache.max_accelerated_files=20000
opcache.validate_timestamps=1
opcache.revalidate_freq=2
opcache.save_comments=1
