#!/usr/bin/env bash
# =============================================================================
# FIX 06 (HARD-ish) — Exploitability axis (CISA KEV) in the PDP trust score
# -----------------------------------------------------------------------------
# Gap: the PDP scores CVEs only by criticalCount/highCount. A "critical" CVE
#      with no public exploit is treated the same as one being actively
#      exploited. We add a KEV (CISA Known-Exploited Vulnerabilities) axis.
#
# Code (already in infras/pdp/pdp_controller.py):
#   * reads vulnerabilityID list from each Trivy VulnerabilityReport
#   * loads the KEV CVE-id set from ConfigMap security/kev-catalog (key kev.txt)
#   * subtracts WEIGHT_KEV when any of a pod's CVEs is on the KEV list
#   * has_kev implies a CVE already exists -> a clean pod is NEVER penalised
#   * WEIGHT_KEV defaults to 0 (inert): deploying the controller changes
#     NOTHING until you populate the catalog AND set the weight.
#
# Sub-commands:
#   status            show code/catalog/weight state
#   apply             regen+deploy the KEV-aware controller (still inert)
#   catalog           fetch CISA KEV -> ConfigMap security/kev-catalog
#   weight <N>        activate: set PDP_WEIGHT_KEV=<N> on the Deployment
#   revert            restore previous controller ConfigMap + weight=0
#
# Recommended order:  apply  ->  catalog  ->  (observe)  ->  weight 40
# Risk: LOW (only sharpens scoring; clean pods stay 100). Activation can move
#       a pod that has a KEV CVE into a lower bucket — that's the intent.
# =============================================================================
source "$(dirname "$0")/lib-common.sh"

FIX="06-pdp-kev-score"
NS="security"
DEPLOY="zta-pdp"
CM="zta-pdp-script"
KEV_CM="kev-catalog"
KEV_KEY="kev.txt"
PY_SRC="$FIXES_DIR/../pdp/pdp_controller.py"
REQ_SRC="$FIXES_DIR/../pdp/requirements.txt"
REPO_CM="$FIXES_DIR/../k8s-yaml/pdp/20-configmap.yaml"
KEV_URL="${KEV_URL:-https://www.cisa.gov/sites/default/files/feeds/known_exploited_vulnerabilities.json}"

_regen_cm() {
  # Rebuild 20-configmap.yaml from the edited source (same logic as
  # scripts/zta-deploy-pdp.sh --regen-cm-only) so the deployed CM matches code.
  python3 - "$PY_SRC" "$REQ_SRC" "$REPO_CM" <<'PYEOF'
import sys
py, req, out = sys.argv[1], sys.argv[2], sys.argv[3]
script = open(py).read()
reqs = open(req).read()
def indent(s, p="    "):
    return "\n".join(p + l if l else p.rstrip() for l in s.split("\n"))
header = ("# ===========================================================================\n"
          "# PDP Controller — Python script packaged as ConfigMap (no image build).\n"
          "# Regenerated by infras/fixes/06-pdp-kev-score.sh\n"
          "# ===========================================================================\n")
cm = f"""apiVersion: v1
kind: ConfigMap
metadata:
  name: zta-pdp-script
  namespace: security
  labels:
    zta.job7189/tier: T1
    zta.job7189/role: pdp
    zta.job7189/team: security
    zta.job7189/data-classification: confidential
    zta.job7189/env: prod
    zta.job7189/exposure: cluster-only
data:
  pdp_controller.py: |
{indent(script)}
  requirements.txt: |
{indent(reqs)}
"""
open(out, "w").write(header + cm)
import yaml
list(yaml.safe_load_all(open(out)))   # validate
print("regenerated + validated:", out)
PYEOF
}

_weight_now() {
  "$KUBECTL" -n "$NS" get deploy "$DEPLOY" \
    -o jsonpath='{range .spec.template.spec.containers[0].env[?(@.name=="PDP_WEIGHT_KEV")]}{.value}{end}' 2>/dev/null
}

status() {
  need_kubectl
  if "$KUBECTL" -n "$NS" get cm "$CM" -o jsonpath='{.data.pdp_controller\.py}' 2>/dev/null | grep -q "WEIGHT_KEV"; then
    ok "controller deployed WITH KEV code"
  else
    warn "controller deployed WITHOUT KEV code — run: $0 apply"
  fi
  local n; n="$("$KUBECTL" -n "$NS" get cm "$KEV_CM" -o jsonpath="{.data.kev\.txt}" 2>/dev/null | grep -c 'CVE-' || true)"
  log "kev-catalog CVE count: ${n:-0}"
  log "PDP_WEIGHT_KEV on deployment: '$(_weight_now)' (empty/0 = inert)"
}

apply() {
  need_kubectl
  [[ -f "$PY_SRC" ]] || die "source not found: $PY_SRC"
  grep -q "WEIGHT_KEV" "$PY_SRC" || die "source python has no KEV code — wrong checkout?"

  local bdir; bdir="$(new_backup_dir "$FIX")"
  dump_obj "$NS" "cm/$CM"         "$bdir/configmap.yaml"
  dump_obj "$NS" "deploy/$DEPLOY" "$bdir/deployment.yaml"

  log "Regenerating ConfigMap from source..."
  _regen_cm
  confirm "Apply KEV-aware PDP ConfigMap and restart $NS/$DEPLOY? (KEV stays INERT, weight=0)"
  "$KUBECTL" apply -f "$REPO_CM"
  "$KUBECTL" -n "$NS" rollout restart "deploy/$DEPLOY"
  "$KUBECTL" -n "$NS" rollout status  "deploy/$DEPLOY" --timeout=360s
  ok "Deployed. KEV axis is INERT until you run: $0 catalog && $0 weight 40"
  ok "Backup at: $bdir"
}

catalog() {
  need_kubectl
  command -v curl >/dev/null 2>&1 || die "curl required to fetch the KEV feed"
  command -v python3 >/dev/null 2>&1 || die "python3 required to parse the KEV feed"
  local tmp; tmp="$(mktemp)"
  log "Fetching CISA KEV feed: $KEV_URL"
  curl -fsSL --retry 3 "$KEV_URL" -o "$tmp" || die "KEV download failed (network/proxy?)"
  local kev; kev="$(mktemp)"
  python3 - "$tmp" > "$kev" <<'PYEOF'
import sys, json
d = json.load(open(sys.argv[1]))
ids = sorted({v.get("cveID","").strip() for v in d.get("vulnerabilities", []) if v.get("cveID")})
print("\n".join(ids))
PYEOF
  local n; n="$(grep -c 'CVE-' "$kev" || true)"
  [[ "${n:-0}" -gt 0 ]] || die "parsed 0 CVE IDs — feed format changed?"
  log "Parsed $n KEV CVE IDs; writing ConfigMap $NS/$KEV_CM"
  "$KUBECTL" -n "$NS" create configmap "$KEV_CM" \
    --from-file="$KEV_KEY=$kev" --dry-run=client -o yaml | "$KUBECTL" apply -f -
  rm -f "$tmp" "$kev"
  ok "kev-catalog populated with $n CVE IDs"
}

weight() {
  need_kubectl
  local n="${1:-}"; [[ "$n" =~ ^[0-9]+$ ]] || die "usage: $0 weight <non-negative-integer>"
  local bdir; bdir="$(new_backup_dir "$FIX")"
  dump_obj "$NS" "deploy/$DEPLOY" "$bdir/deployment.yaml"
  confirm "Set PDP_WEIGHT_KEV=$n on $NS/$DEPLOY? (pods with a KEV CVE may drop bucket)"
  # add-or-replace the env var
  "$KUBECTL" -n "$NS" set env "deploy/$DEPLOY" "PDP_WEIGHT_KEV=$n"
  "$KUBECTL" -n "$NS" rollout status "deploy/$DEPLOY" --timeout=360s
  ok "PDP_WEIGHT_KEV=$n active. Revert weight: $0 weight 0"
}

revert() {
  need_kubectl
  local bdir; bdir="$(resolve_revert_dir "$FIX" "${1:-}")"
  if [[ -f "$bdir/configmap.yaml" ]]; then
    log "Restoring previous PDP ConfigMap from $bdir"
    "$KUBECTL" apply -f "$bdir/configmap.yaml"
  fi
  "$KUBECTL" -n "$NS" set env "deploy/$DEPLOY" "PDP_WEIGHT_KEV=0" 2>/dev/null || true
  "$KUBECTL" -n "$NS" rollout restart "deploy/$DEPLOY"
  "$KUBECTL" -n "$NS" rollout status  "deploy/$DEPLOY" --timeout=360s
  ok "Reverted controller + KEV weight=0 (catalog ConfigMap left in place; delete with: kubectl -n $NS delete cm $KEV_CM)"
}

case "${1:-status}" in
  apply)   apply ;;
  catalog) catalog ;;
  weight)  weight "${2:-}" ;;
  revert)  revert "${2:-}" ;;
  status)  status ;;
  *) die "usage: $0 {status | apply | catalog | weight <N> | revert [backup-dir]}" ;;
esac
