replicaCount: 1

registry:
  # url: "docker-registry.registry.svc.cluster.local:5000"
  url: "172.17.0.1:5000"
image:
  repository: job7189/identity-service
  tag: v2.8.17
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  className: "nginx"
  host: "change-me.local"

env:
  APP_ENV: production

appEnvTmpfsSizeLimit: "16Mi"

resources:
  app:
    requests:
      cpu: "200m"
      memory: "256Mi"
    limits:
      cpu: "800m"
      memory: "768Mi"
  sidecar:
    requests:
      cpu: "15m"
      memory: "24Mi"
    limits:
      cpu: "120m"
      memory: "96Mi"
  init:
    requests:
      cpu: "10m"
      memory: "16Mi"
    limits:
      cpu: "80m"
      memory: "64Mi"

# Image digests for init/sidecar images to satisfy admission policy
initImages:
  busybox: "busybox@sha256:73aaf090f3d85aa34ee199857f03fa3a95c8ede2ffd4cc2cdb5b94e566b11662"

sidecarImages:
  envWatcher: "alpine@sha256:de0eb0b3f2a47ba1eb89389859a9bd88b28e82f5826b6969ad604979713c2d4f"

redis:
  enabled: false
  # Use digest to satisfy admission policy requiring image digests (signed by zta-cosign-key)
  image: 100.74.189.43:5443/job7189/redis@sha256:d7fcf65186e011faaa401b5e6edf5147e9dd01353984c795e515f6fee7dfbe6e
  port: 6379
  resources:
    requests:
      cpu: "25m"
      memory: "64Mi"
    limits:
      cpu: "200m"
      memory: "192Mi"

vault:
  extraSecret: false
  extraSecretTemplate: ""

# SPIRE spiffe-helper sidecar (provides JWT-SVID for Vault auth/jwt). Pinned by digest.
spiffeHelper:
  image: "ghcr.io/spiffe/spiffe-helper@sha256:4d9863034d8f95d5b6592095b57a38828e54b4e92f66d744a6ed353f6fc0bf7f"