replicaCount: 1

registry:
  # url: "docker-registry.registry.svc.cluster.local:5000"
  url: "172.17.0.1:5000"
image:
  repository: job7189/identity-service
  tag: v2.8.17
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  className: "nginx"
  host: "change-me.local"

env:
  APP_ENV: production

appEnvTmpfsSizeLimit: "16Mi"

resources:
  app:
    requests:
      cpu: "200m"
      memory: "256Mi"
    limits:
      cpu: "800m"
      memory: "768Mi"
  sidecar:
    requests:
      cpu: "15m"
      memory: "24Mi"
    limits:
      cpu: "120m"
      memory: "96Mi"
  init:
    requests:
      cpu: "10m"
      memory: "16Mi"
    limits:
      cpu: "80m"
      memory: "64Mi"

redis:
  enabled: false
  image: redis:7
  port: 6379
  resources:
    requests:
      cpu: "25m"
      memory: "64Mi"
    limits:
      cpu: "200m"
      memory: "192Mi"

vault:
  extraSecret: false
  extraSecretTemplate: ""
