apiVersion: v1
kind: Pod
metadata:
  name: disk-checker-srv05
  namespace: kube-system
spec:
  nodeName: 7189srv05
  priorityClassName: system-node-critical
  tolerations:
  - key: "node.kubernetes.io/disk-pressure"
    operator: "Exists"
    effect: "NoSchedule"
  containers:
  - name: checker
    image: alpine
    command: ["/bin/sh", "-c", "echo '=== DU VAR/LIB ===' && du -hxd 1 /host/var/lib 2>/dev/null && echo '=== DU VAR/LOG ===' && du -hxd 1 /host/var/log 2>/dev/null && echo '=== DU OTHER ===' && du -hxd 1 /host/usr /host/opt /host/home /host/tmp 2>/dev/null"]
    volumeMounts:
    - name: host-root
      mountPath: /host
  volumes:
  - name: host-root
    hostPath:
      path: /
  restartPolicy: Never
