replicaCount: 1

internalReloadToken: "candidate-secure-reload-token-22222"

image:
  repository: job7189/candidate-service
  fullImage: "100.74.189.43:5443/job7189/candidate@sha256:9fa42a6bad234a30fb9fae7f13b16660e315194174f0171f36c63db82c9e3c80"
  pullPolicy: Always

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  host: "candidate.job7189.local"

redis:
  enabled: true

env:
  APP_NAME: "Job7189 Candidate Service"
  DB_CONNECTION: mongodb
  DB_HOST: mongodb.data.svc.cluster.local
  DB_PORT: "27017"
  DB_DATABASE: job7189_candidate_db
  CACHE_DRIVER: "redis"
  REDIS_HOST: "candidate-service-redis"
  REDIS_PORT: "6379"
  CACHE_PREFIX: candidate_
  LOG_CHANNEL: "stderr"
  LOG_LEVEL: "info"

vault:
  role: candidate-service
  extraSecret: false
  secretTemplate: |
    {{- with secret "database/creds/candidate-service" -}}
    DB_USERNAME="{{ .Data.username }}"
    DB_PASSWORD="{{ .Data.password }}"
    LEASE_ID="{{ .Data.lease_id }}"
    {{- end }}

zta:
  role: api
  tier: T2
  env: prod
  dataClassification: internal
  exposure: internal
  team: backend
