replicaCount: 1

internalReloadToken: "candidate-secure-reload-token-22222"

image:
  repository: job7189/candidate-service
  fullImage: "100.74.189.43:5443/job7189/candidate-service@sha256:dc23e51cdb268e7578850e0a61a69afc72be0ff5900370ae355599dd843750cf"
  pullPolicy: Always

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  host: "candidate.job7189.local"

redis:
  enabled: true

env:
  APP_NAME: "Job7189 Candidate Service"
  DB_CONNECTION: mysql
  DB_HOST: mysql.data.svc.cluster.local
  DB_PORT: "3306"
  DB_DATABASE: job7189_candidate_db
  CACHE_DRIVER: "redis"
  REDIS_HOST: "candidate-service-redis"
  REDIS_PORT: "6379"
  CACHE_PREFIX: candidate_
  LOG_CHANNEL: "stderr"
  LOG_LEVEL: "info"

vault:
  role: candidate-service
  extraSecret: false
  secretTemplate: |
    {{- with secret "database/creds/candidate-service" -}}
    DB_USERNAME="{{ .Data.username }}"
    DB_PASSWORD="{{ .Data.password }}"
    LEASE_ID="{{ .Data.lease_id }}"
    {{- end }}

zta:
  role: api
  tier: T2
  env: prod
  dataClassification: internal
  exposure: internal
  team: backend
