replicaCount: 1

internalReloadToken: "communication-secure-reload-token-33333"

image:
  repository: job7189/communication-service
  fullImage: "100.74.189.43:5000/job7189/communication@sha256:2a2605f7c94a4d335e12bc1b3bbcb2ee51885066b7bb1946cb02a169a68bbf68"
  pullPolicy: Always

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  host: "communication.job7189.local"

redis:
  enabled: true

env:
  APP_NAME: "Job7189 Communication Service"
  DB_CONNECTION: mysql
  DB_HOST: mysql.data.svc.cluster.local
  DB_PORT: "3306"
  DB_DATABASE: job7189_communication_db
  CACHE_DRIVER: "redis"
  REDIS_HOST: "communication-service-redis"
  REDIS_PORT: "6379"
  CACHE_PREFIX: communication_
  LOG_CHANNEL: "stderr"
  LOG_LEVEL: "info"

vault:
  role: communication-service
  extraSecret: false
  secretTemplate: |
    {{- with secret "database/creds/communication-service" -}}
    DB_USERNAME="{{ .Data.username }}"
    DB_PASSWORD="{{ .Data.password }}"
    LEASE_ID="{{ .Data.lease_id }}"
    {{- end }}

zta:
  role: api
  tier: T2
  env: prod
  dataClassification: internal
  exposure: internal
  team: backend
