replicaCount: 1

internalReloadToken: "hiring-secure-reload-token-11111"

image:
  repository: job7189/hiring-service
  fullImage: "100.74.189.43:5443/job7189/hiring-service@sha256:9a78ccf3565cc92498a6daaeab015b43e4cf534b4b2a49c76da19031dcacfef8"
  pullPolicy: Always

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  host: "hiring.job7189.local"

redis:
  enabled: true

env:
  APP_NAME: "Job7189 Hiring Service"
  DB_CONNECTION: mysql
  DB_HOST: mysql.data.svc.cluster.local
  DB_PORT: "3306"
  DB_DATABASE: job7189_hiring_db
  CACHE_DRIVER: "redis"
  REDIS_HOST: "hiring-service-redis"
  REDIS_PORT: "6379"
  CACHE_PREFIX: hiring_
  LOG_CHANNEL: "stderr"
  LOG_LEVEL: "info"

vault:
  role: hiring-service
  extraSecret: false
  secretTemplate: |
    {{- with secret "database/creds/hiring-service" -}}
    DB_USERNAME="{{ .Data.username }}"
    DB_PASSWORD="{{ .Data.password }}"
    LEASE_ID="{{ .Data.lease_id }}"
    {{- end }}

zta:
  role: api
  tier: T2
  env: prod
  dataClassification: internal
  exposure: internal
  team: backend
