replicaCount: 1

internalReloadToken: "identity-secure-reload-token-99999"

image:
  repository: job7189/identity
  fullImage: "100.74.189.43:5443/job7189/identity@sha256:06716f333c4cba88805fcb47c1a0689d55630fee03bf5d3533ac35a9e77dce83"
  pullPolicy: Always

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  host: "identity.job7189.local"

redis:
  enabled: true

env:
  APP_NAME: "Job7189 Identity Service"
  DB_CONNECTION: mysql
  DB_HOST: mysql.data.svc.cluster.local
  DB_PORT: "3306"
  DB_DATABASE: job7189_identity_db
  CACHE_DRIVER: "redis"
  REDIS_HOST: "identity-service-redis"
  REDIS_PORT: "6379"
  CACHE_PREFIX: identity_
  LOG_CHANNEL: "stderr"
  LOG_LEVEL: "info"

vault:
  role: identity-service
  extraSecret: false
  secretTemplate: |
    {{- with secret "database/creds/identity-service" -}}
    DB_USERNAME="{{ .Data.username }}"
    DB_PASSWORD="{{ .Data.password }}"
    LEASE_ID="{{ .Data.lease_id }}"
    {{- end }}

zta:
  role: api
  tier: T2
  env: prod
  dataClassification: internal
  exposure: internal
  team: backend
