replicaCount: 1

internalReloadToken: "job-secure-reload-token-67890"

image:
  repository: job7189/job-service
  fullImage: "100.74.189.43:5000/job7189/job@sha256:54babfc486cd4293e7e46f74d7af537611a77e96a497b85cb5bba8ab9c8f041a"
  pullPolicy: Always

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  host: "job.job7189.local"

redis:
  enabled: true

env:
  APP_NAME: "Job7189 Job Service"
  DB_CONNECTION: mysql
  DB_HOST: mysql.data.svc.cluster.local
  DB_PORT: "3306"
  DB_DATABASE: job7189_job_db
  CACHE_DRIVER: "redis"
  REDIS_HOST: "job-service-redis"
  REDIS_PORT: "6379"
  CACHE_PREFIX: job_
  LOG_CHANNEL: "stderr"
  LOG_LEVEL: "info"

vault:
  role: job-service
  extraSecret: false
  secretTemplate: |
    {{- with secret "database/creds/job-service" -}}
    DB_USERNAME="{{ .Data.username }}"
    DB_PASSWORD="{{ .Data.password }}"
    LEASE_ID="{{ .Data.lease_id }}"
    {{- end }}

zta:
  role: api
  tier: T2
  env: prod
  dataClassification: internal
  exposure: internal
  team: backend
