replicaCount: 1

internalReloadToken: "storage-secure-reload-token-44444"

image:
  repository: job7189/storage-service
  fullImage: "100.74.189.43:5443/job7189/storage-service@sha256:55cc23d1f6c993c01e1e369b9f3413aa213b23a5e3d589128794b9b06060286d"
  pullPolicy: Always

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  host: "storage.job7189.local"

redis:
  enabled: true

env:
  APP_NAME: "Job7189 Storage Service"
  DB_CONNECTION: mysql
  DB_HOST: mysql.data.svc.cluster.local
  DB_PORT: "3306"
  DB_DATABASE: job7189_storage_db
  CACHE_DRIVER: "redis"
  REDIS_HOST: "storage-service-redis"
  REDIS_PORT: "6379"
  CACHE_PREFIX: storage_
  LOG_CHANNEL: "stderr"
  LOG_LEVEL: "info"
  FILESYSTEM_DISK: "minio"
  MINIO_ENDPOINT: "http://100.108.231.127:30900"
  MINIO_URL: "http://100.108.231.127:30900/job7189-storage"
  MINIO_BUCKET: "job7189-storage"
  MINIO_REGION: "us-east-1"
  MINIO_USE_PATH_STYLE_ENDPOINT: "true"
  MINIO_KEY: "minioadmin"
  MINIO_SECRET: "minioadmin"
  AWS_ENDPOINT: "http://100.108.231.127:30900"
  AWS_URL: "http://100.108.231.127:30900/job7189-storage"
  AWS_BUCKET: "job7189-storage"
  AWS_DEFAULT_REGION: "us-east-1"
  AWS_USE_PATH_STYLE_ENDPOINT: "true"
  AWS_ACCESS_KEY_ID: "minioadmin"
  AWS_SECRET_ACCESS_KEY: "minioadmin"

vault:
  role: storage-service
  extraSecret: false
  secretTemplate: |
    {{- with secret "database/creds/storage-service" -}}
    DB_USERNAME="{{ .Data.username }}"
    DB_PASSWORD="{{ .Data.password }}"
    LEASE_ID="{{ .Data.lease_id }}"
    {{- end }}

zta:
  role: api
  tier: T2
  env: prod
  dataClassification: internal
  exposure: internal
  team: backend
