replicaCount: 1

internalReloadToken: "storage-secure-reload-token-44444"

image:
  repository: job7189/storage-service
  fullImage: "100.74.189.43:5000/job7189/storage@sha256:fa9a8fb5074308aeee57faa065e545eb45f30498ef3f41c93c0a29147309ec56"
  pullPolicy: Always

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  host: "storage.job7189.local"

redis:
  enabled: true

env:
  APP_NAME: "Job7189 Storage Service"
  DB_CONNECTION: mysql
  DB_HOST: mysql.data.svc.cluster.local
  DB_PORT: "3306"
  DB_DATABASE: job7189_storage_db
  CACHE_DRIVER: "redis"
  REDIS_HOST: "storage-service-redis"
  REDIS_PORT: "6379"
  CACHE_PREFIX: storage_
  LOG_CHANNEL: "stderr"
  LOG_LEVEL: "info"
  MINIO_ENDPOINT: "http://192.168.112.158:8080"

vault:
  role: storage-service
  extraSecret: false
  secretTemplate: |
    {{- with secret "database/creds/storage-service" -}}
    DB_USERNAME="{{ .Data.username }}"
    DB_PASSWORD="{{ .Data.password }}"
    LEASE_ID="{{ .Data.lease_id }}"
    {{- end }}

zta:
  role: api
  tier: T2
  env: prod
  dataClassification: internal
  exposure: internal
  team: backend
