replicaCount: 1

internalReloadToken: "workspace-secure-reload-token-12345"

image:
  repository: job7189/workspace-service
  fullImage: "100.74.189.43:5443/job7189/workspace@sha256:f4dfefeb9c1934e003c92414d3cc16213642eda10802953a1f05aaea2526214e"
  pullPolicy: Always

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  host: "workspace.job7189.local"

redis:
  enabled: true

env:
  APP_NAME: "Job7189 Workspace Service"
  DB_CONNECTION: mysql
  DB_HOST: mysql.data.svc.cluster.local
  DB_PORT: "3306"
  DB_DATABASE: job7189_workspace_db
  CACHE_PREFIX: workspace_
  LOG_CHANNEL: "stderr"
  LOG_LEVEL: "debug"
  IDENTITY_SERVICE_URL: "http://identity-service"
  REDIS_HOST: "workspace-service-redis"
  SUPER_ADMIN_WORKSPACE_ID: "019bb56a-58cf-7241-b150-4e6c39f8ce4c"

vault:
  role: workspace-service
  extraSecret: false
  secretTemplate: |
    {{- with secret "database/creds/workspace-service" -}}
    DB_USERNAME="{{ .Data.username }}"
    DB_PASSWORD="{{ .Data.password }}"
    LEASE_ID="{{ .Data.lease_id }}"
    {{- end }}

zta:
  role: api
  tier: T2
  env: prod
  dataClassification: internal
  exposure: internal
  team: backend
