[supervisord]
nodaemon=true
user=root
logfile=/dev/null
logfile_maxbytes=0
pidfile=/var/run/supervisord.pid

[group:laravel-service]
programs=nginx,php8-fpm,laravel-schedule,laravel-queue,kafka-consume-identity,watch-env

; --- NGINX & PHP (Giữ nguyên) ---
[program:nginx]
priority=10
command=/usr/sbin/nginx -g 'daemon off;'
autostart=true
autorestart=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0

[program:php8-fpm]
priority=5
command=/usr/local/sbin/php-fpm -R
autostart=true
autorestart=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0

; --- SỬA LỖI SCHEDULE ---
[program:laravel-schedule]
command=php /var/www/artisan schedule:run
autostart=true
autorestart=false ; <--- QUAN TRỌNG: Phải là false
startretries=0    ; <--- Không thử lại
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0

; --- QUEUE CHÍNH (REDIS) ---
[program:laravel-queue]
command=php /var/www/artisan queue:work redis --queue=cv_processing,notifications,default --sleep=3 --tries=3 --memory=128
autostart=true
autorestart=true
numprocs=1
process_name=%(program_name)s_%(process_num)02d
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0

[program:kafka-consume-identity]
command=php /var/www/artisan kafka:consume-identity
autostart=true
autorestart=true
numprocs=1
redirect_stderr=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stopwaitsecs=3600
environment=APP_ENV=production
 
[program:watch-env]
command=/usr/local/bin/watch-env.sh
autostart=true
autorestart=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0